services:
  db:
    image: mysql:8.0
    container_name: vidaplena_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pw_taller
      MYSQL_DATABASE: vidaplena
      MYSQL_USER: vidaplena_app
      MYSQL_PASSWORD: vidaplena_app_pw
    ports:
      - "3306:3306"
    volumes:
      - vidaplena_db_data:/var/lib/mysql
      - ./backend/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pw_taller"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: vidaplena_backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: vidaplena_app
      DB_PASSWORD: vidaplena_app_pw
      DB_NAME: vidaplena
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: vidaplena_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  vidaplena_db_data: